USE WAREHOUSE

DELETE FROM UMIESZCZENIE_REKLAMY_W_ARTYKULE
DELETE FROM ARTYKUL
DELETE FROM AUTOR
DELETE FROM REKLAMA
DELETE FROM DATA_ZDARZENIA
DELETE FROM GODZINA
DELETE FROM UMOWA

DROP TABLE UMIESZCZENIE_REKLAMY_W_ARTYKULE
DROP TABLE ARTYKUL
DROP TABLE AUTOR
DROP TABLE REKLAMA
DROP TABLE DATA_ZDARZENIA
DROP TABLE GODZINA
DROP TABLE UMOWA
